services:
  db:
    image: postgres:15
    container_name: ecommerce_db_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce_monitoring-etl-db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  etl:
    build: .
    container_name: etl_app_container
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app

volumes:
  pgdata: